// Generated by `pnpm brand:apply`. Do not edit directly.
pub const PRODUCT_NAME: &str = "Luna Telepresence";
pub const SHORT_NAME: &str = "Luna";
pub const DATA_DIRECTORY_NAME: &str = "Luna Telepresence";
pub const RECORDINGS_DIRECTORY_NAME: &str = "Luna Telepresence Recordings";
pub const WEBSITE_URL: &str = "https://github.com/rgatewood/luna-telepresence";
pub const UPDATES_ENABLED: bool = false;
