import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const config = JSON.parse(fs.readFileSync(path.join(root, 'brand.config.json'), 'utf8'));

const required = [
  'productName',
  'shortName',
  'packageName',
  'identifier',
  'dataDirectoryName',
  'modelLibraryDirectoryName',
  'recordingsDirectoryName',
  'websiteUrl',
];
for (const key of required) {
  if (!config[key] || typeof config[key] !== 'string') {
    throw new Error(`brand.config.json requires a non-empty string for ${key}`);
  }
}

const packagePath = path.join(root, 'package.json');
const packageJson = JSON.parse(fs.readFileSync(packagePath, 'utf8'));
packageJson.name = config.packageName;
fs.writeFileSync(packagePath, `${JSON.stringify(packageJson, null, 4)}\n`);

const tauriPath = path.join(root, 'src-tauri', 'tauri.conf.json');
const tauri = JSON.parse(fs.readFileSync(tauriPath, 'utf8'));
tauri.productName = config.productName;
tauri.identifier = config.identifier;
tauri.app.windows[0].title = config.productName;
tauri.bundle.createUpdaterArtifacts = Boolean(config.updates?.enabled);
tauri.app.security.capabilities[0].permissions = tauri.app.security.capabilities[0].permissions
  .filter((permission) => permission !== 'updater:default');
if (config.updates?.enabled) {
  if (!config.updates.endpoint || !config.updates.publicKey) {
    throw new Error('Enabled updates require updates.endpoint and updates.publicKey');
  }
  tauri.plugins = tauri.plugins ?? {};
  tauri.plugins.updater = {
    pubkey: config.updates.publicKey,
    endpoints: [config.updates.endpoint],
  };
  tauri.app.security.capabilities[0].permissions.push('updater:default');
} else {
  tauri.plugins = tauri.plugins ?? {};
  tauri.plugins.updater = {
    pubkey: '',
    endpoints: [],
  };
}
fs.writeFileSync(tauriPath, `${JSON.stringify(tauri, null, 4)}\n`);

const rustString = (value) => JSON.stringify(value);
const generated = `// Generated by \`pnpm brand:apply\`. Do not edit directly.\n` +
  `pub const PRODUCT_NAME: &str = ${rustString(config.productName)};\n` +
  `pub const SHORT_NAME: &str = ${rustString(config.shortName)};\n` +
  `pub const DATA_DIRECTORY_NAME: &str = ${rustString(config.dataDirectoryName)};\n` +
  `pub const MODEL_LIBRARY_DIRECTORY_NAME: &str = ${rustString(config.modelLibraryDirectoryName)};\n` +
  `pub const RECORDINGS_DIRECTORY_NAME: &str = ${rustString(config.recordingsDirectoryName)};\n` +
  `pub const WEBSITE_URL: &str = ${rustString(config.websiteUrl)};\n` +
  `pub const UPDATES_ENABLED: bool = ${Boolean(config.updates?.enabled)};\n`;
fs.writeFileSync(path.join(root, 'src-tauri', 'src', 'brand.generated.rs'), generated);

console.log(`Applied brand: ${config.productName}`);
